version: "3.3"
services:
  frontend:
    container_name: frontend
    build: ./src/main/resources/frontend
    image: krystalsimmonds/sfia-three-react
    ports:
      - target: 3000
        published: 3000
    depends_on:
      - backend

  backend:
    container_name: backend
    build: ./
    image: krystalsimmonds/sfia-three-spring
    ports:
      - target: 9500
        published: 9500
        protocol: tcp

  #  database:
  #    container_name: database
  #    image: mysql:5.7
  #    ports:
  #      - target: 3306
  #        published: 3306

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - target: 80
        published: 80
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend