// Ansible vars_file containing variable values from Terraform.
// Generated by Terraform mgmt configuration.
// hosts public dns - for building project
env.jenkins_user="ubuntu@"
env.test_user="ubuntu@"
env.bastion="ubuntu@ec2-35-177-238-87.eu-west-2.compute.amazonaws.com"
// host key generated for ssh into vms
env.EC2_private_key="j-key"
// project variables to pass for database
env.TEST_DATABASE_URI="mysql+pymysql://admin:password@test-db.c66nh3bppyv6.eu-west-2.rds.amazonaws.com:3306/testdb"
env.DATABASE_URI="mysql+pymysql://admin:password@prod-db.c66nh3bppyv6.eu-west-2.rds.amazonaws.com:3306/users"
env.SECRET_KEY="password"
env.MYSQL_ROOT_PASSWORD="password"
env.DB_PASSWORD="password"
env.testvm_connection="mysql -h test-db.c66nh3bppyv6.eu-west-2.rds.amazonaws.com:3306 -P 3306 -u admin -ppassword"
